// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using appTutorial.EntityFramework;

namespace appTutorial.EntityFramework.Migrations
{
    [DbContext(typeof(TestsDbContext))]
    partial class TestsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("appTutorial.EntityFramework.DTOs.TestDto", b =>
                {
                    b.Property<Guid>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AutorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestDiscription")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Testname")
                        .HasColumnType("TEXT");

                    b.HasKey("TestID");

                    b.ToTable("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
